//! Builders for large params struct from autogenerated bindings.
//!
//! The bindings contain many massive structs which are used as parameters to
//! functions in the API. This module provides builders to simplify creating
//! these struct. They each have a `new()` method which has the minimum required
//! parameters for the struct. Other options

use std::ffi::c_void;

use crate::sys::nvEncodeAPI::{
	NV_ENC_BUFFER_FORMAT, NV_ENC_INPUT_RESOURCE_TYPE, NV_ENC_PIC_FLAGS, NV_ENC_PIC_PARAMS, NV_ENC_PIC_PARAMS_VER,
	NV_ENC_REGISTER_RESOURCE, NV_ENC_REGISTER_RESOURCE_VER,
};

impl NV_ENC_PIC_PARAMS {
	/// Create an EOS empty frame that is used at the
	/// end of encoding to flush the encoder.
	#[must_use]
	pub fn end_of_stream() -> Self {
		NV_ENC_PIC_PARAMS {
			version: NV_ENC_PIC_PARAMS_VER,
			encodePicFlags: NV_ENC_PIC_FLAGS::NV_ENC_PIC_FLAG_EOS as u32,
			..Default::default()
		}
	}
}

impl NV_ENC_REGISTER_RESOURCE {
	/// Builder for [`NV_ENC_REGISTER_RESOURCE`].
	///
	/// # Arguments
	///
	/// * `resource_type` - Specifies the type of resource to be registered.
	///   Supported values are:
	///   - [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX`],
	///   - [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_CUDADEVICEPTR`],
	///   - [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_OPENGL_TEX`]
	/// * `width` - Input frame width.
	/// * `height` - Input frame height.
	/// * `resource_to_register` - Handle to the resource that is being
	///   registered. In the case of
	///   [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_CUDADEVICEPTR`],
	///   this should be a `CUdeviceptr` which you can get from
	///   `cuExternalMemoryGetMappedBuffer`.
	/// * `buffer_format` - Buffer format of resource to be registered.
	#[must_use]
	pub fn new(
		resource_type: NV_ENC_INPUT_RESOURCE_TYPE,
		width: u32,
		height: u32,
		resource_to_register: *mut c_void,
		buffer_format: NV_ENC_BUFFER_FORMAT,
	) -> Self {
		NV_ENC_REGISTER_RESOURCE {
			version: NV_ENC_REGISTER_RESOURCE_VER,
			resourceType: resource_type,
			width,
			height,
			pitch: width,
			resourceToRegister: resource_to_register,
			registeredResource: std::ptr::null_mut(),
			bufferFormat: buffer_format,
			..Default::default()
		}
	}

	/// Set the input buffer pitch.
	///
	/// - For [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX`]
	///   resources, set this to 0.
	/// - For [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_CUDADEVICEPTR`]
	///   resources, set this to the pitch as obtained from `cuMemAllocPitch()`,
	///   or to the width in **bytes** (if this resource was created by using
	///   `cuMemAlloc()`). This value must be a multiple of 4.
	/// - For [`NV_ENC_INPUT_RESOURCE_TYPE::NV_ENC_INPUT_RESOURCE_TYPE_OPENGL_TEX`]
	///   resources, set this to the texture width multiplied by the number of
	///   components in the texture format.
	#[must_use]
	pub fn pitch(mut self, pitch: u32) -> Self {
		self.pitch = pitch;
		self
	}

	// TODO: Add other options
}
