import { describe, expect, test } from "bun:test";
import { authorize } from "./claims.ts";
import { GrantSchema, RequestSchema } from "./contract.ts";
import { generate } from "./generate.ts";
import { load, loadPublic, sign, verify } from "./key.ts";
import { findKey, loadSet, verifyWith } from "./set.ts";

// Tests that the JS @moq/auth package can load keys generated by the Rust
// moq-auth crate and verify tokens signed by Rust, and vice versa.

describe("Rust-generated fixtures", () => {
	// moq auth generate --out /tmp/rust-hs256.jwk
	const RUST_HS256_KEY = JSON.stringify({
		alg: "HS256",
		key_ops: ["verify", "sign"],
		kty: "oct",
		k: "jvS2B_SKkvhtObaiKg9n2vq_Iqdus-nVCVVYBWf0BQA",
		kid: "d55b1f13e6bda281",
	});

	// moq auth sign --key /tmp/rust-hs256.jwk --root demo --publish 'alice/**' --subscribe 'bob/**'
	const RUST_HS256_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQ1NWIxZjEzZTZiZGEyODEifQ.eyJyb290IjoiZGVtbyIsInB1Ymxpc2giOlsiYWxpY2UvKioiXSwic3Vic2NyaWJlIjpbImJvYi8qKiJdfQ.OuaQY4hHKpBLvTK-9ZUv2oxiqXTGisng-cg2GcqrgdY";

	// A token scoped to the root path. Rust skips serializing an empty `root`, so the
	// claims arrive with no `root` field at all.
	// moq auth sign --key /tmp/rust-hs256.jwk --publish 'alice/**' --subscribe 'bob/**'
	const RUST_HS256_TOKEN_EMPTY_ROOT =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQ1NWIxZjEzZTZiZGEyODEifQ.eyJwdWJsaXNoIjpbImFsaWNlLyoqIl0sInN1YnNjcmliZSI6WyJib2IvKioiXX0.f1uYbrxNNyGg_0TkRWXHRhU0K_HKlOjeiddwHqppK-0";

	// moq auth generate --algorithm EdDSA --out /tmp/rust-eddsa-private.jwk --public /tmp/rust-eddsa-public.jwk
	const RUST_EDDSA_PRIVATE_KEY = JSON.stringify({
		alg: "EdDSA",
		key_ops: ["sign", "verify"],
		kty: "OKP",
		crv: "Ed25519",
		x: "S9n3tEG677fSNpa0Ftf46OPBte5y1pTwvm4fPkEw_Z8",
		d: "EhFsuE3CFkJoQpZCT2Wwr6YF7ZwjsaEIgbwO4Uc4b5U",
		kid: "dfab9113ea85dc27",
	});

	const RUST_EDDSA_PUBLIC_KEY = JSON.stringify({
		alg: "EdDSA",
		key_ops: ["verify"],
		kty: "OKP",
		crv: "Ed25519",
		x: "S9n3tEG677fSNpa0Ftf46OPBte5y1pTwvm4fPkEw_Z8",
		kid: "dfab9113ea85dc27",
	});

	// moq auth sign --key /tmp/rust-eddsa-private.jwk --root room --publish 'stream1/**' --publish 'stream2/**' --subscribe 'feed1/**'
	const RUST_EDDSA_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRmYWI5MTEzZWE4NWRjMjcifQ.eyJyb290Ijoicm9vbSIsInB1Ymxpc2giOlsic3RyZWFtMS8qKiIsInN0cmVhbTIvKioiXSwic3Vic2NyaWJlIjpbImZlZWQxLyoqIl19.dpZ_p-eyKxaw6bRZp7sfKjmao04MwPuPqbu744bucPjiQVNfGZodfeyEk-fsY79fa9YSbjM1m6DPw3Wg7pzRBA";

	test("load Rust HS256 key", () => {
		const key = load(RUST_HS256_KEY);
		expect(key.alg).toBe("HS256");
		expect(key.kid).toBe("d55b1f13e6bda281");
		expect(key.kty).toBe("oct");
	});

	test("verify Rust HS256 token", async () => {
		const key = load(RUST_HS256_KEY);
		const claims = await verify(key, RUST_HS256_TOKEN);
		expect(claims.root).toBe("demo");
		expect(claims.publish).toEqual(["alice/**"]);
		expect(claims.subscribe).toEqual(["bob/**"]);
	});

	test("verify Rust HS256 token scoped to the root path", async () => {
		const key = load(RUST_HS256_KEY);
		const claims = await verify(key, RUST_HS256_TOKEN_EMPTY_ROOT);
		expect(claims.root).toBe("");
		expect(claims.publish).toEqual(["alice/**"]);
		expect(claims.subscribe).toEqual(["bob/**"]);

		// An empty root grants its patterns wherever the connection lands.
		const permissions = authorize(claims, "alice");
		expect(permissions.subscribe.toJSON()).toEqual([]);
		expect(permissions.publish.toJSON()).toEqual(["**"]);
	});

	test("sign with Rust HS256 key and verify roundtrip", async () => {
		const key = load(RUST_HS256_KEY);
		const token = await sign(key, { root: "js-test", publish: ["pub1/**"], subscribe: ["sub1/**"] });
		const claims = await verify(key, token);
		expect(claims.root).toBe("js-test");
		expect(claims.publish).toEqual(["pub1/**"]);
		expect(claims.subscribe).toEqual(["sub1/**"]);
	});

	test("load Rust EdDSA keys", () => {
		const privateKey = load(RUST_EDDSA_PRIVATE_KEY);
		expect(privateKey.alg).toBe("EdDSA");
		expect(privateKey.kty).toBe("OKP");

		const publicKey = loadPublic(RUST_EDDSA_PUBLIC_KEY);
		expect(publicKey.alg).toBe("EdDSA");
		expect(publicKey.kty).toBe("OKP");
	});

	test("sign with Rust EdDSA private key and verify with public key", async () => {
		const privateKey = load(RUST_EDDSA_PRIVATE_KEY);
		const publicKey = loadPublic(RUST_EDDSA_PUBLIC_KEY);
		const token = await sign(privateKey, { root: "js-eddsa", publish: ["test/**"] });
		const claims = await verify(publicKey, token);
		expect(claims.root).toBe("js-eddsa");
		expect(claims.publish).toEqual(["test/**"]);
	});

	test("verify Rust EdDSA token with public key", async () => {
		const key = loadPublic(RUST_EDDSA_PUBLIC_KEY);
		const claims = await verify(key, RUST_EDDSA_TOKEN);
		expect(claims.root).toBe("room");
		expect(claims.publish).toEqual(["stream1/**", "stream2/**"]);
		expect(claims.subscribe).toEqual(["feed1/**"]);
	});

	// moq auth generate --root project --publish 'live/**' --subscribe 'watch/**' --out /tmp/scoped.jwk
	const RUST_SCOPED_KEY = JSON.stringify({
		alg: "HS256",
		key_ops: ["verify", "sign"],
		kty: "oct",
		k: "pLDMYsYrp6vZLQbefVzHXN6P4wc1ADTLn4L7xzi1Qm4",
		kid: "e396f70014db9fe9",
		scope: { root: "project", publish: ["live/**"], subscribe: ["watch/**"] },
	});

	// moq auth sign --key /tmp/scoped.jwk --root project --publish 'live/room/**' --subscribe 'watch/**'
	const RUST_SCOPED_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImUzOTZmNzAwMTRkYjlmZTkifQ.eyJyb290IjoicHJvamVjdCIsInB1Ymxpc2giOlsibGl2ZS9yb29tLyoqIl0sInN1YnNjcmliZSI6WyJ3YXRjaC8qKiJdfQ.JHx-OFoj5chiC33R6zVeaeHYUPCTEYKBfCETPLwrwtc";

	test("load a Rust key's scope", () => {
		const key = load(RUST_SCOPED_KEY);
		expect(key.scope).toEqual({ root: "project", publish: ["live/**"], subscribe: ["watch/**"] });
	});

	test("verify a Rust token signed within its key scope", async () => {
		const key = load(RUST_SCOPED_KEY);
		const claims = await verify(key, RUST_SCOPED_TOKEN);
		expect(claims.publish).toEqual(["live/room/**"]);
		expect(claims.subscribe).toEqual(["watch/**"]);
	});

	test("JS enforces the same scope Rust does", async () => {
		const key = load(RUST_SCOPED_KEY);

		// Rust rejects this exact pair with "token capabilities exceed the key scope":
		// moq auth sign --key /tmp/scoped.jwk --root project --publish 'other/**'
		await expect(sign(key, { root: "project", publish: ["other/**"] })).rejects.toThrow("exceed the key scope");

		// ...and accepts the grants Rust signed into RUST_SCOPED_TOKEN. The encoding
		// is not compared: JS orders the header differently and stamps `iat`.
		const token = await sign(key, { root: "project", publish: ["live/room/**"], subscribe: ["watch/**"] });
		const claims = await verify(key, token);
		expect(claims.publish).toEqual(["live/room/**"]);
		expect(claims.subscribe).toEqual(["watch/**"]);
	});
});

describe("Rust-generated JWK Set", () => {
	// A JWK Set written by the Rust `KeySet::to_str()`, holding two HS256 keys.
	// cargo run --example _fixture   (see the moq-auth crate)
	const RUST_JWKS = JSON.stringify({
		keys: [
			{
				alg: "HS256",
				key_ops: ["sign", "verify"],
				kty: "oct",
				k: "jvS2B_SKkvhtObaiKg9n2vq_Iqdus-nVCVVYBWf0BQA",
				kid: "d55b1f13e6bda281",
			},
			{
				alg: "HS256",
				key_ops: ["verify", "sign"],
				kty: "oct",
				k: "Fp8kipWUJeUFqeSqWym_tRC_tyI8z-QpqopIGrbrD68",
				kid: "second-key",
			},
		],
	});

	// Signed by the Rust `KeySet::sign()`, so the kid header selects the first key.
	const RUST_JWKS_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQ1NWIxZjEzZTZiZGEyODEifQ.eyJyb290IjoiZGVtbyIsInB1Ymxpc2giOlsiYWxpY2UvKioiXSwic3Vic2NyaWJlIjpbImJvYi8qKiJdfQ.OuaQY4hHKpBLvTK-9ZUv2oxiqXTGisng-cg2GcqrgdY";

	test("load a Rust JWKS", () => {
		const set = loadSet(RUST_JWKS);
		expect(set.keys.length).toBe(2);
		expect(findKey(set, "d55b1f13e6bda281")?.alg).toBe("HS256");
		expect(findKey(set, "second-key")?.alg).toBe("HS256");
	});

	test("verify a Rust KeySet-signed token, selecting the key by kid", async () => {
		const set = loadSet(RUST_JWKS);
		const claims = await verifyWith(set, RUST_JWKS_TOKEN);
		expect(claims.root).toBe("demo");
		expect(claims.publish).toEqual(["alice/**"]);
		expect(claims.subscribe).toEqual(["bob/**"]);
	});

	test("a token whose kid is absent from the Rust JWKS is rejected", async () => {
		const set = loadSet(RUST_JWKS);
		const stranger = await generate("HS256", "not-in-the-set");
		const token = await sign(stranger, { root: "demo", publish: ["alice/**"] });
		await expect(verifyWith(set, token)).rejects.toThrow(/Cannot find key with kid not-in-the-set/);
	});
});

describe("wrong key rejects token", () => {
	// moq auth generate --out /tmp/rust-hs256.jwk
	const RUST_HS256_KEY = JSON.stringify({
		alg: "HS256",
		key_ops: ["verify", "sign"],
		kty: "oct",
		k: "jvS2B_SKkvhtObaiKg9n2vq_Iqdus-nVCVVYBWf0BQA",
		kid: "d55b1f13e6bda281",
	});

	// moq auth sign --key /tmp/rust-hs256.jwk --root demo --publish 'alice/**' --subscribe 'bob/**'
	const RUST_HS256_TOKEN =
		"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImQ1NWIxZjEzZTZiZGEyODEifQ.eyJyb290IjoiZGVtbyIsInB1Ymxpc2giOlsiYWxpY2UvKioiXSwic3Vic2NyaWJlIjpbImJvYi8qKiJdfQ.OuaQY4hHKpBLvTK-9ZUv2oxiqXTGisng-cg2GcqrgdY";

	test("different HS256 key rejects Rust token", async () => {
		const wrongKey = await generate("HS256");
		await expect(verify(wrongKey, RUST_HS256_TOKEN)).rejects.toThrow();
	});

	test("unrelated path is not authorized by the token", async () => {
		const key = load(RUST_HS256_KEY);
		const claims = await verify(key, RUST_HS256_TOKEN);
		expect(() => authorize(claims, "wrong-root")).toThrow();
	});

	test("tampered token is rejected", async () => {
		const key = load(RUST_HS256_KEY);
		// Flip a character in the signature
		const tampered = RUST_HS256_TOKEN.slice(0, -1) + (RUST_HS256_TOKEN.at(-1) === "A" ? "B" : "A");
		await expect(verify(key, tampered)).rejects.toThrow();
	});

	test("EdDSA token rejected by HS256 key", async () => {
		const key = load(RUST_HS256_KEY);
		// moq auth sign --key /tmp/rust-eddsa-private.jwk --root room --publish 'stream1/**' --publish 'stream2/**' --subscribe 'feed1/**'
		const eddsaToken =
			"eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRmYWI5MTEzZWE4NWRjMjcifQ.eyJyb290Ijoicm9vbSIsInB1Ymxpc2giOlsic3RyZWFtMS8qKiIsInN0cmVhbTIvKioiXSwic3Vic2NyaWJlIjpbImZlZWQxLyoqIl19.dpZ_p-eyKxaw6bRZp7sfKjmao04MwPuPqbu744bucPjiQVNfGZodfeyEk-fsY79fa9YSbjM1m6DPw3Wg7pzRBA";
		await expect(verify(key, eddsaToken)).rejects.toThrow();
	});

	test("garbage token is rejected", async () => {
		const key = load(RUST_HS256_KEY);
		await expect(verify(key, "not-a-jwt")).rejects.toThrow();
	});
});

describe("Rust-serialized contract", () => {
	// The exact bytes `moq_auth::Request` and `Grant` serialize to; see
	// request::tests::end_serializes_to_the_cross_language_vector and
	// grant::tests::serializes_to_the_cross_language_vector in the Rust crate.
	const RUST_REQUEST =
		'{"id":"00ff","event":"end","reason":"expired","duration":1.5,"bytes":{"sent":10,"received":20},"node":"relay-1","transport":"websocket","remote":"203.0.113.9:4433","path":"/demo/room","query":"jwt=abc"}';
	const RUST_GRANT =
		'{"publish":["alice/**"],"subscribe":["**"],"root":"pid/room","expires":4102444800,"revalidate":60,"tier":"websocket"}';

	test("parse a request a Rust relay sent", () => {
		const request = RequestSchema.parse(JSON.parse(RUST_REQUEST));
		expect(request.transport).toBe("websocket");
		if (request.event !== "end") throw new Error("expected an end");
		expect(request.reason).toBe("expired");
		expect(request.duration).toBe(1.5);
		expect(request.bytes).toEqual({ sent: 10, received: 20 });
	});

	test("a grant built here is what a Rust relay reads", () => {
		const grant = GrantSchema.parse({
			publish: ["alice/**"],
			subscribe: ["**"],
			root: "pid/room",
			expires: 4102444800,
			revalidate: 60,
			tier: "websocket",
		});
		expect(JSON.stringify(grant)).toBe(RUST_GRANT);
	});
});
