[log]
# Enable debug logging for development.
# The RUST_LOG environment variable will take precedence.
level = "debug"

[server]
# Listen for QUIC connections on UDP:4445
# Sometimes IPv6 causes issues; try 127.0.0.1:4445 instead.
listen = "[::]:4445"

# Generate a self-signed certificate for the server.
# You should use a real certificate in production.
tls.generate = ["localhost"]

[web.http]
# Listen for HTTP and WebSocket (TCP) connections on the given address.
listen = "[::]:4445"

# Clustering: connect to the root node.
# In this example, leaf nodes don't connect directly to each other; traffic gets proxied through the root.
# `connect` can be an array to connect to multiple peers, creating a tiered CDN.
[cluster]
connect = "localhost:4443"
token = "dev/root.jwt"

[client]
# QUIC uses TLS to have the client verify the server's identity.
# However if you're not worried about man-in-the-middle attacks, you can disable verification:
tls.disable_verify = true

# A better approach is to generate a server certificate and configure the client to accept it.
#
# If the server has a certificate generated by a public root CA (ex. Let's Encrypt), then that will work if the client connects to the indiciated domain.
# ex. a cert for *.moq.dev will only be allowed if the root/node configuration below matches.
#
# Alternatively, you can generate a self-signed root CA and configure the client to accept it.
# tls.root = ["/path/to/root.pem"]
#
# This can be much more secure because the server doesn't need to be publically accessible.
# ex. You could host the root at a private `.internal` domain and generate a matching certificate.

[auth]
# `just auth-key` will populate this file.
key = "dev/root.jwk"

# Allow anonymous publishing and subscribing for this prefix.
public = "anon"
