//! Transport and lifecycle failure drills against a real relay.
//!
//! Delivery working on a healthy loopback says nothing about cancellation, a
//! relay dying mid-group, a publisher coming back, or bursts crossing a relay
//! cluster. Each drill here disrupts a live session over real QUIC and asserts
//! three things:
//!
//! 1. the fault actually activated, recorded as a value the test prints;
//! 2. the failure surfaced as a terminal result, never a clean finish or a hang;
//! 3. the resources it owned were released.
//!
//! Each drill runs in two lanes, generated by [`lanes!`] so a scenario cannot
//! drift between them: `loopback`, and `impaired`, where every client reaches
//! the relay through a seeded [`moq_shaper`] that delays, jitters, drops,
//! reorders, and rate-limits the path both ways (and, across a cluster, the
//! peer link between relays too). A drill that only passes on loopback is a
//! finding, not a flake.
//!
//! `no_publisher_never_delivers` is the negative control: the same harness with
//! nothing publishing must report failure, so a drill that passes because no
//! data ever moved cannot hide here.
//!
//! See `test/drill/README.md` for the recipe, the sensitivity proof that each
//! drill fails when its recovery behavior is removed, and the loom/fuzz cases
//! covering the primitives underneath.
#![cfg(all(feature = "noq", feature = "websocket"))]

use std::time::Duration;

use moq_relay::{Config, Relay};
use moq_tokio::moq_net;

/// Ceiling for anything a drill waits on. Every wait is bounded, so a broken
/// handoff fails as a timeout with a message instead of hanging the suite.
const TIMEOUT: Duration = Duration::from_secs(10);

/// How long a stalled reader sits on its hands, and how far the publisher runs
/// ahead of it. Long enough that the backlog is unambiguous, short enough to
/// stay a unit test.
const STALL: Duration = Duration::from_millis(300);
const STALL_GROUPS: usize = 8;

/// The track every drill publishes.
const TRACK: &str = "drill";

/// The impaired lane's treatment, the same both ways: a workable path, not a
/// hostile one, and the drills' own budgets (a 2s idle timeout, 10s waits) hold
/// under it unchanged. The loss is 5% because a drill only sends a few hundred
/// datagrams, and at 2% that is a drop or two, which barely exercises recovery.
fn impairment() -> moq_shaper::Profile {
	moq_shaper::Profile {
		delay: Duration::from_millis(20),
		jitter: Duration::from_millis(5),
		loss: 0.05,
		reorder: 0.02,
		rate: Some(moq_shaper::Rate {
			bits_per_second: 10_000_000,
			// One datagram's worth, so a back-to-back flight is paced rather
			// than let through whole.
			burst: 1500,
			queue: Duration::from_millis(100),
		}),
	}
}

/// Which path a drill's clients take to the relay.
#[derive(Clone, Copy, Debug)]
enum Lane {
	Loopback,
	Impaired,
}

/// Run a drill in every [`Lane`], as a module of one test per lane.
macro_rules! lanes {
	($drill:ident) => {
		mod $drill {
			#[tokio::test]
			async fn loopback() {
				super::$drill(super::Lane::Loopback).await
			}

			#[tokio::test]
			async fn impaired() {
				super::$drill(super::Lane::Impaired).await
			}
		}
	};
}

/// The path clients dial, and the shaper on it in the impaired lane.
///
/// The shaper runs on the test's runtime rather than the relay's, so killing
/// the relay leaves the path up, like a network outliving the server behind it.
struct Path {
	url: url::Url,
	shaper: Option<moq_shaper::Shaper>,
}

impl Path {
	async fn start(lane: Lane, relay: &RelayHost) -> Self {
		Self::shaped(lane, relay, impairment()).await
	}

	/// [`Self::start`], treating the impaired lane to `profile` both ways.
	async fn shaped(lane: Lane, relay: &RelayHost, profile: moq_shaper::Profile) -> Self {
		let Lane::Impaired = lane else {
			return Self {
				url: relay.url(),
				shaper: None,
			};
		};

		// A fresh seed each run explores more of the decision space; the one
		// printed below replays a failure's decisions.
		let seed = match std::env::var("MOQ_SHAPER_SEED") {
			Ok(seed) => seed.parse().expect("MOQ_SHAPER_SEED is not a u64"),
			Err(_) => rand::random(),
		};
		let shaper = moq_shaper::Shaper::bind(moq_shaper::Config {
			bind: "127.0.0.1:0".parse().unwrap(),
			target: format!("127.0.0.1:{}", relay.port).parse().unwrap(),
			seed,
			up: profile.clone(),
			down: profile,
		})
		.await
		.expect("start the shaper");
		println!("impaired: MOQ_SHAPER_SEED={seed}, profile {:?}", shaper.config().up);

		Self {
			url: format!("https://{}/drill", shaper.addr()).parse().unwrap(),
			shaper: Some(shaper),
		}
	}

	/// Fail the drill unless the impairment it ran under actually acted.
	///
	/// A profile that silently did nothing would turn this lane into a second
	/// loopback run that passes for free.
	fn verify(mut self) {
		if let Some(shaper) = self.shaper.take() {
			let stats = shaper.verify().unwrap_or_else(|err| panic!("impaired: {err:#}"));
			println!("impaired: {stats}");
		}
	}
}

impl Drop for Path {
	fn drop(&mut self) {
		// A drill that failed before `verify` still reports what the path did.
		if let Some(shaper) = &self.shaper {
			println!("impaired: {}", shaper.stats());
		}
	}
}

/// A relay on its own runtime, so a drill can kill it the way a crash does.
///
/// Aborting the `run` task is not enough: the relay accept loop spawns a task per
/// connection, and those keep serving a relay whose accept loop is gone. Owning
/// the runtime means one shutdown takes the accept loop, every connection task,
/// and the UDP socket at once.
struct RelayHost {
	port: u16,
	/// `None` once killed, which is also what stops [`Drop`] from killing twice.
	runtime: Option<tokio::runtime::Runtime>,
}

impl RelayHost {
	/// Bind a relay running `config` and wait for it to be ready to accept.
	async fn start(config: Config) -> Self {
		// Process-global; every drill in this binary races to be first.
		let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();

		let runtime = tokio::runtime::Builder::new_multi_thread()
			.worker_threads(2)
			.enable_all()
			.build()
			.expect("build relay runtime");

		let (ready, bound) = tokio::sync::oneshot::channel();
		runtime.spawn(async move {
			match Relay::load(config).await {
				Ok(relay) => {
					let _ = ready.send(Ok(relay.addr()));
					let _ = relay.run().await;
				}
				Err(err) => {
					let _ = ready.send(Err(format!("{err:#}")));
				}
			}
		});

		let addr = tokio::time::timeout(TIMEOUT, bound)
			.await
			.expect("relay startup timed out")
			.expect("relay task vanished during startup")
			.expect("relay failed to load");
		let port = addr.expect("relay did not bind UDP").port();

		Self {
			port,
			runtime: Some(runtime),
		}
	}

	/// Kill the relay: drop the runtime, taking every task and socket with it.
	///
	/// The shutdown blocks, so it runs on a blocking thread rather than in the
	/// test's own runtime. The timeout only bounds how long a stuck worker
	/// delays the test; the tasks are already gone when it expires.
	async fn kill(&mut self) {
		let runtime = self.runtime.take().expect("relay already killed");
		tokio::task::spawn_blocking(move || runtime.shutdown_timeout(Duration::from_secs(1)))
			.await
			.expect("relay shutdown panicked");
	}

	/// The URL clients dial. `https` is WebTransport over QUIC.
	fn url(&self) -> url::Url {
		format!("https://127.0.0.1:{}/drill", self.port)
			.parse()
			.expect("parse relay url")
	}
}

/// A public relay on loopback with a generated certificate, on `port` or an ephemeral one.
fn relay_config(port: Option<u16>) -> Config {
	let mut config = Config::default();
	config.listen.bind = Some(format!("127.0.0.1:{}", port.unwrap_or_default()).parse().unwrap());
	config.listen.tls.generate = vec!["localhost".into()];
	config.auth.public = vec![moq_auth::Pattern::all()];
	config
}

impl Drop for RelayHost {
	fn drop(&mut self) {
		// A drill that ends (or panics) with the relay still up must not leave
		// its threads and socket behind for the next one to trip over.
		if let Some(runtime) = self.runtime.take() {
			runtime.shutdown_background();
		}
	}
}

/// A client that trusts the relay's generated certificate and speaks QUIC only.
///
/// The WebSocket fallback is off on purpose: these drills are about the QUIC
/// path, and a silent fallback would grade a different transport than the one
/// under test.
fn client(url: &url::Url) -> moq_tokio::Client {
	client_over(url, quic())
}

/// The drills' QUIC tuning for a client.
fn quic() -> moq_tokio::quic::Config {
	// A killed relay sends no CONNECTION_CLOSE, so the idle timeout is the only
	// thing that ever tells a client it is gone. The 30s default would put that
	// discovery past every budget here. The keep-alive is an eighth of it, so a
	// busy runner has to stall eight times over before a live session is mistaken
	// for a dead one.
	let mut quic = moq_tokio::quic::Config::default();
	quic.idle_timeout = Duration::from_secs(2);
	quic.keep_alive = Duration::from_millis(250);
	quic
}

/// [`client`], with `quic` as its transport tuning.
fn client_over(url: &url::Url, quic: moq_tokio::quic::Config) -> moq_tokio::Client {
	let mut config = moq_tokio::connect::Config::default();
	config.url = Some(url.clone());
	config.bind = Some("127.0.0.1:0".parse().expect("parse client bind"));
	config.tls.insecure = Some(true);
	config.websocket.enabled = Some(false);

	// Fast enough to keep a relay bounce inside the drill's budget, paced enough
	// that the loop is still a backoff.
	config.backoff.initial = Duration::from_millis(50);
	config.backoff.max = Duration::from_millis(200);
	config.backoff.timeout = Duration::from_secs(5);

	config.init(quic).expect("client init")
}

/// Append one finished group carrying `payload`.
fn write_group(track: &mut moq_net::track::Producer, payload: &[u8]) {
	let mut group = track.append_group().expect("append group");
	group
		.write_frame(moq_net::Timestamp::ZERO, payload)
		.expect("write frame");
	group.finish().expect("finish group");
}

/// Read the next group's first frame, failing the drill on a timeout, a clean
/// finish, or an empty group.
async fn read_group(reader: &mut Reader, what: &str) -> (u64, Vec<u8>) {
	let group = tokio::time::timeout(TIMEOUT, reader.groups.recv_group())
		.await
		.unwrap_or_else(|_| panic!("{what}: no group within {TIMEOUT:?}"))
		.unwrap_or_else(|err| panic!("{what}: track aborted: {err}"))
		.unwrap_or_else(|| panic!("{what}: track finished instead of delivering a group"));
	let sequence = group.sequence;

	let mut group = group;
	let frame = tokio::time::timeout(TIMEOUT, group.read_frame())
		.await
		.unwrap_or_else(|_| panic!("{what}: no frame within {TIMEOUT:?}"))
		.unwrap_or_else(|err| panic!("{what}: group aborted: {err}"))
		.unwrap_or_else(|| panic!("{what}: group finished with no frame"));

	(sequence, frame.payload.to_vec())
}

/// Read until `want` arrives, tolerating groups the disruption truncated.
///
/// A drill that resumes after an outage is asking whether new content flows, not
/// what happened to the groups caught in it, so a group whose frames went with
/// the old session is skipped here. A track-level failure is still fatal: that
/// says the subscription itself did not survive.
async fn read_until(reader: &mut Reader, want: &[u8], what: &str) {
	tokio::time::timeout(TIMEOUT, async {
		loop {
			let mut group = match reader.groups.recv_group().await {
				Ok(Some(group)) => group,
				Ok(None) => panic!("{what}: the track finished instead of resuming"),
				Err(err) => panic!("{what}: the track aborted: {err}"),
			};
			if let Ok(Some(frame)) = group.read_frame().await
				&& frame.payload == want
			{
				return;
			}
		}
	})
	.await
	.unwrap_or_else(|_| panic!("{what}: {} never arrived", String::from_utf8_lossy(want)));
}

/// Everything a drill holds on the subscribing side of one broadcast.
struct Reader {
	/// The broadcast the session feeds. Outlives the subscription so a drill can
	/// watch what a cancel or a session loss does to it.
	broadcast: moq_net::broadcast::Consumer,
	/// The local mirror of the publisher's track: `latest()` is what arrived,
	/// whatever the subscriber below has bothered to read.
	track: moq_net::track::Consumer,
	groups: moq_net::track::Subscriber,
}

/// Wait for `path` to be announced, then subscribe to [`TRACK`].
async fn subscribe(origin: &moq_net::origin::Consumer, path: &str) -> Reader {
	// `routed_broadcast` parks until a route covers the path; `request_broadcast`
	// would race the announcement and report a live broadcast as unroutable.
	let broadcast = tokio::time::timeout(TIMEOUT, origin.routed_broadcast(path))
		.await
		.expect("announcement timed out")
		.expect("origin closed before announcing");

	let track = broadcast.track(TRACK).expect("track");
	let groups = tokio::time::timeout(TIMEOUT, track.subscribe(None))
		.await
		.expect("subscribe timed out")
		.expect("subscribe rejected");

	Reader {
		broadcast,
		track,
		groups,
	}
}

/// Drill: stall a reader until a backlog builds, then cancel it.
///
/// The fault is a live subscription with unread groups stacked up behind it.
/// Cancelling there has to end cleanly on both counts: the handles that
/// subscription fed are released rather than left parked for a reader that will
/// never return, and the relay keeps serving everyone else.
///
/// What it deliberately does not assert is the publisher going idle. That
/// edge is the origin front's: it drops the source track when the last local
/// reader leaves, and is covered by moq-net's origin tests. This drill grades
/// the cancel itself: the stalled reader's handles release, and everyone else
/// keeps being served. The rejoin below is the half of that behavior worth
/// grading here.
async fn cancel_under_backpressure_releases_the_reader(lane: Lane) {
	let relay = RelayHost::start(relay_config(None)).await;
	let path = Path::start(lane, &relay).await;
	let url = path.url.clone();

	let publisher = moq_tokio::origin::spawn();
	let broadcast = publisher.create_broadcast("live").expect("create broadcast");
	broadcast.announce(Default::default()).expect("announce broadcast");
	let mut track = broadcast.create_track(TRACK, None).expect("create track");
	let publish_session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_publisher(&publisher)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("publisher connect timed out")
	.expect("publisher connect failed");

	let subscriber = moq_tokio::origin::spawn();
	let subscribed = subscriber.consume();
	let subscribe_session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_subscriber(subscriber)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("subscriber connect timed out")
	.expect("subscriber connect failed");

	write_group(&mut track, b"first");
	let mut reader = subscribe(&subscribed, "live").await;
	let (first, payload) = read_group(&mut reader, "before the stall").await;
	assert_eq!(payload, b"first", "delivery is broken before the drill even starts");

	// The stall: the reader stops asking while the publisher runs ahead of it.
	for i in 0..STALL_GROUPS {
		write_group(&mut track, format!("stalled {i}").as_bytes());
		tokio::time::sleep(STALL / STALL_GROUPS as u32).await;
	}

	// Fault activation: the groups reached the subscriber and stacked up behind a
	// reader that never asked for them, so the cancel below lands on a live
	// subscription with a real backlog rather than on an idle one. Nothing blocks
	// a moq publisher (`write_frame` is synchronous, and a reader that falls too
	// far behind is shed rather than waited for), so an unread backlog is what
	// backpressure looks like from here.
	let backlog = tokio::time::timeout(TIMEOUT, async {
		loop {
			match reader.track.latest() {
				Some(latest) if latest >= first + STALL_GROUPS as u64 => return latest - first,
				_ => tokio::time::sleep(Duration::from_millis(10)).await,
			}
		}
	})
	.await
	.unwrap_or_else(|_| {
		panic!(
			"the stalled reader is only {:?} groups behind: nothing was queued, so there is no backlog to cancel under",
			reader.track.latest().map(|latest| latest - first)
		)
	});
	println!("fault activated: cancelling with {backlog} unread groups queued");

	// Nothing has been released yet, so the release below cannot be reporting a
	// state that was already true.
	assert!(
		!reader.broadcast.is_closed(),
		"the subscriber's broadcast closed while it was still reading"
	);

	// The cancel, with the backlog outstanding.
	let cancelled = reader.broadcast.clone();
	drop(reader);
	drop(subscribe_session);

	// Resource release: everything that session was feeding is closed, rather
	// than left parked on a subscription nobody will ever serve again.
	tokio::time::timeout(TIMEOUT, cancelled.closed())
		.await
		.expect("the cancelled subscriber's broadcast never closed");
	println!("resource released: the cancelled broadcast closed");

	// ...and the relay survived it: a fresh subscriber still gets served, off the
	// upstream subscription the cancel left in place.
	let rejoin = moq_tokio::origin::spawn();
	let rejoined = rejoin.consume();
	let rejoin_session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_subscriber(rejoin)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("rejoin connect timed out")
	.expect("rejoin connect failed");
	let mut rejoined_reader = subscribe(&rejoined, "live").await;
	write_group(&mut track, b"after cancel");
	read_until(&mut rejoined_reader, b"after cancel", "after the cancel").await;

	drop(rejoined_reader);
	drop(rejoin_session);
	drop(publish_session);
	path.verify();
}

lanes!(cancel_under_backpressure_releases_the_reader);

/// Drill: kill the relay mid-group, then bring it back.
///
/// Two things have to hold. An interrupted track must abort, because a clean
/// finish means "the publisher is done" and silently truncating a live stream
/// into one is the worst possible failure mode. And the reconnect loop has to
/// restore service: the dead session's broadcast closes with it, and a fresh
/// subscribe through the same origin resumes once the relay returns.
async fn relay_killed_mid_group_aborts_then_resumes(lane: Lane) {
	let mut relay = RelayHost::start(relay_config(None)).await;
	let port = relay.port;
	let path = Path::start(lane, &relay).await;
	let url = path.url.clone();

	let publisher = moq_tokio::origin::spawn();
	let broadcast = publisher.create_broadcast("live").expect("create broadcast");
	broadcast.announce(Default::default()).expect("announce broadcast");
	let mut track = broadcast.create_track(TRACK, None).expect("create track");
	let mut publish_loop = client(&url).publish(publisher.consume()).expect("no connect url");

	let subscriber = moq_tokio::origin::spawn();
	let subscribed = subscriber.consume();
	let mut subscribe_loop = client(&url).consume(subscriber).expect("no connect url");

	write_group(&mut track, b"before");
	let mut reader = subscribe(&subscribed, "live").await;
	let (_, payload) = read_group(&mut reader, "before the kill").await;
	assert_eq!(payload, b"before", "delivery is broken before the drill even starts");

	// A group that is open, delivered as far as its first frame, and waited on for
	// a second: the kill lands mid-group rather than in the quiet between them.
	// Nothing more is written, so what the reader is waiting for cannot arrive
	// ahead of the kill and turn this into a race.
	let mut open = track.append_group().expect("append group");
	open.write_frame(moq_net::Timestamp::ZERO, b"read".as_ref())
		.expect("write frame");
	let mut open_reader = tokio::time::timeout(TIMEOUT, reader.groups.recv_group())
		.await
		.expect("open group timed out")
		.expect("track aborted")
		.expect("track finished");
	tokio::time::timeout(TIMEOUT, open_reader.read_frame())
		.await
		.expect("open frame timed out")
		.expect("open group aborted")
		.expect("open group finished");

	relay.kill().await;

	// Terminal result: the unread half of the open group fails. `Ok(None)` here
	// would be the relay's death passing for the publisher finishing.
	let err = tokio::time::timeout(TIMEOUT, open_reader.read_frame())
		.await
		.expect("the interrupted group never resolved")
		.expect_err("the interrupted group reported a clean finish");
	println!("fault activated: interrupted group aborted with {err}");

	// Fault activation: both loops noticed they lost the relay.
	expect_status(&mut subscribe_loop, moq_tokio::Status::Disconnected, "subscriber").await;
	expect_status(&mut publish_loop, moq_tokio::Status::Disconnected, "publisher").await;

	let relay = RelayHost::start(relay_config(Some(port))).await;
	assert_eq!(relay.port, port, "relay bound the wrong port");

	expect_status(&mut subscribe_loop, moq_tokio::Status::Connected, "subscriber").await;
	expect_status(&mut publish_loop, moq_tokio::Status::Connected, "publisher").await;

	// The outage is observed, not hidden: the broadcast the dead session fed closed
	// with it, so the old subscription ends rather than reading from a stale route.
	let err = match tokio::time::timeout(TIMEOUT, reader.groups.recv_group())
		.await
		.expect("the interrupted subscription never resolved")
	{
		Err(err) => err,
		Ok(_) => panic!("the interrupted subscription kept going instead of aborting"),
	};
	println!("fault activated: interrupted subscription aborted with {err}");
	drop(reader);

	// Resumed delivery through the same subscriber origin: the reconnected
	// publisher re-announced, and a fresh subscribe rides the new session.
	open.finish().expect("finish the interrupted group");
	write_group(&mut track, b"after");
	let mut reader = subscribe(&subscribed, "live").await;
	read_until(&mut reader, b"after", "after the restart").await;

	drop(reader);
	drop(subscribe_loop);
	drop(publish_loop);
	drop(relay);
	path.verify();
}

lanes!(relay_killed_mid_group_aborts_then_resumes);

/// Wait for a reconnect loop to report `want`, failing with what it said instead.
async fn expect_status(reconnect: &mut moq_tokio::Connection, want: moq_tokio::Status, who: &str) {
	loop {
		let status = tokio::time::timeout(TIMEOUT, reconnect.status())
			.await
			.unwrap_or_else(|_| panic!("{who}: no status change within {TIMEOUT:?}, wanted {want:?}"))
			.unwrap_or_else(|err| panic!("{who}: reconnect loop gave up: {err}"));
		if status == want {
			return;
		}
	}
}

/// Drill: interrupt a publisher, then republish the same name.
///
/// A crashed publisher must withdraw its broadcast rather than leave a name
/// announced that nothing serves, and the replacement has to be new content: a
/// subscriber that re-consumes the same name after a republish gets what the
/// new publisher is sending, never the previous one's cache.
async fn interrupted_publisher_republishes_new_content(lane: Lane) {
	let relay = RelayHost::start(relay_config(None)).await;
	let path = Path::start(lane, &relay).await;
	let url = path.url.clone();

	let subscriber = moq_tokio::origin::spawn();
	let subscribed = subscriber.consume();
	let subscribe_session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_subscriber(subscriber)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("subscriber connect timed out")
	.expect("subscriber connect failed");
	let mut announced = subscribed.announced();

	let first = moq_tokio::origin::spawn();
	let broadcast = first.create_broadcast("live").expect("create broadcast");
	broadcast.announce(Default::default()).expect("announce broadcast");
	let mut track = broadcast.create_track(TRACK, None).expect("create track");
	let first_session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_publisher(&first)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("publisher connect timed out")
	.expect("publisher connect failed");

	write_group(&mut track, b"original");
	expect_announce(&mut announced, "live", true, "the first publisher").await;
	let mut reader = subscribe(&subscribed, "live").await;
	let (_, payload) = read_group(&mut reader, "before the interrupt").await;
	assert_eq!(payload, b"original", "delivery is broken before the drill even starts");

	// The interrupt: the session goes first, so the relay loses the publisher
	// with no finish and no unannounce, which is what a crashed publisher looks
	// like. Dropping the broadcast while the session was still up would send a
	// clean unannounce instead and never reach the crash path. The rest goes
	// after, including the subscriber's handles, so nothing local keeps the dead
	// broadcast alive for the assertions below.
	drop(first_session);
	drop(reader);
	drop(track);
	drop(broadcast);
	drop(first);

	// Terminal result: the name stops being announced. Nothing told the relay
	// the broadcast ended, so this is the proof that losing the publisher's
	// session withdraws what it announced rather than parking subscribers on it.
	expect_announce(&mut announced, "live", false, "the interrupted publisher").await;
	println!("fault activated: the interrupted publisher's broadcast was withdrawn");

	// Restore: the same name, a new publisher, different content.
	let second = moq_tokio::origin::spawn();
	let broadcast = second.create_broadcast("live").expect("re-create broadcast");
	broadcast.announce(Default::default()).expect("announce broadcast");
	let mut track = broadcast.create_track(TRACK, None).expect("re-create track");
	let second_session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_publisher(&second)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("republisher connect timed out")
	.expect("republisher connect failed");

	write_group(&mut track, b"replacement");
	expect_announce(&mut announced, "live", true, "the republisher").await;

	let mut reader = subscribe(&subscribed, "live").await;
	let (_, payload) = read_group(&mut reader, "after the republish").await;
	assert_eq!(
		payload, b"replacement",
		"the republished name served the dead publisher's content"
	);

	drop(reader);
	drop(track);
	drop(broadcast);
	drop(second_session);
	drop(subscribe_session);
	path.verify();
}

lanes!(interrupted_publisher_republishes_new_content);

/// Wait for `path` to be announced (`want`) or unannounced (`!want`).
async fn expect_announce(announced: &mut moq_net::announce::Consumer, path: &str, want: bool, who: &str) {
	loop {
		let (update, active) = tokio::time::timeout(TIMEOUT, next_update(announced))
			.await
			.unwrap_or_else(|_| panic!("{who}: no announcement change within {TIMEOUT:?}"))
			.unwrap_or_else(|| panic!("{who}: the announcement stream closed"));
		if update.prefix.as_str() == path && active == want {
			return;
		}
	}
}

/// How many bursts the cross-relay drill sends, and how many one-frame groups
/// each holds: a control channel firing messages back to back.
const BURSTS: u64 = 4;
const BURST_GROUPS: u64 = 30;

/// Each cross-relay group's payload size, about what a small control message is.
const PAYLOAD: usize = 256;

/// How long a cross-relay group may take, from being written, to arrive. Several
/// times the slowest group seen on the impaired path, and a third of the 30s
/// stalls of #4349.
const SETTLE: Duration = Duration::from_secs(10);

/// The cross-relay drill's link: the drills' impairment behind a bottleneck a
/// burst overruns, so its tail waits in the queue or is dropped from it.
fn bursty() -> moq_shaper::Profile {
	moq_shaper::Profile {
		rate: Some(moq_shaper::Rate {
			bits_per_second: 1_000_000,
			burst: 1500,
			queue: Duration::from_millis(50),
		}),
		..impairment()
	}
}

/// QUIC credit tighter than a burst on the impaired lane: fewer concurrent
/// streams than a burst has groups (each group is a stream, each FETCH another),
/// and receive windows of a few groups, so senders wait on MAX_STREAMS and
/// MAX_DATA mid-burst, over a path that loses the frames granting them.
fn credit(lane: Lane, mut quic: moq_tokio::quic::Config) -> moq_tokio::quic::Config {
	if let Lane::Impaired = lane {
		quic.max_streams = Some(16);
		quic.receive_window = Some(4 * PAYLOAD as u64);
		quic.stream_receive_window = Some(2 * PAYLOAD as u64);
	}
	quic
}

/// How a cross-relay group reached the subscriber, or why it never did.
#[derive(Debug)]
enum Outcome {
	/// The live subscription delivered it.
	Live,
	/// A FETCH recovered it after the subscription skipped or lost it.
	Fetched,
	/// The FETCH failed, with this error.
	Failed(String),
	/// The FETCH got no answer within [`SETTLE`].
	Unanswered,
	/// The live subscription opened it but its frame never came within [`SETTLE`].
	Stalled,
}

/// One thing the cross-relay subscriber waits on.
enum Step {
	/// The live subscription's next group.
	Group(Box<moq_net::Result<Option<moq_net::group::Consumer>>>),
	/// A group read or FETCH finished.
	Settled(u64, Outcome),
}

/// Read the one frame of group `sequence`, checking it is the payload written there.
async fn read_payload(mut group: moq_net::group::Consumer, sequence: u64) -> Result<(), String> {
	match group.read_frame().await {
		Ok(Some(frame)) if frame.payload == payload(sequence) => Ok(()),
		Ok(Some(_)) => panic!("group {sequence} carried another group's payload"),
		Ok(None) => Err("finished with no frame".to_string()),
		Err(err) => Err(err.to_string()),
	}
}

/// The payload of group `sequence`: its number, padded to [`PAYLOAD`].
fn payload(sequence: u64) -> Vec<u8> {
	format!("{sequence:>PAYLOAD$}").into_bytes()
}

/// Drill: bursts of one-frame groups cross a two-relay cluster.
///
/// A publisher on an origin relay sends bursts of tens of single-frame groups.
/// A subscriber on an edge relay, which reaches the origin as a cluster peer,
/// reads them with the default subscription (only the newest group) and FETCHes
/// every group below it that the subscription skipped or reset, the way a
/// control channel that must apply every message recovers. In the impaired lane
/// every hop (publisher, peer link, subscriber) runs through a shaper that a
/// burst overruns, and every endpoint grants less QUIC credit than a burst needs.
///
/// Nothing is evicted and no link goes down, so every group has to arrive within
/// [`SETTLE`] of being written; one that does not fails the drill by name, with
/// how it was lost: a FETCH that failed, a FETCH nobody answered, or a live group
/// that stalled. The newest group has to come over the live subscription, since
/// nothing newer can replace it.
async fn bursts_cross_a_cluster(lane: Lane) {
	let mut config = relay_config(None);
	config.quic = credit(lane, config.quic);
	let origin = RelayHost::start(config).await;
	let peer = Path::shaped(lane, &origin, bursty()).await;

	// The edge relay dials the origin as a cluster peer, through its own path.
	let mut peer_url = peer.url.clone();
	peer_url.set_path("/");
	let mut config = relay_config(None);
	config.quic = credit(lane, config.quic);
	config.connect.bind = Some("127.0.0.1:0".parse().unwrap());
	config.connect.tls.insecure = Some(true);
	config.connect.websocket.enabled = Some(false);
	config.cluster.connect = vec![moq_relay::cluster::Peer::new(peer_url.to_string())];
	let edge = RelayHost::start(config).await;

	let publish_path = Path::shaped(lane, &origin, bursty()).await;
	let subscribe_path = Path::shaped(lane, &edge, bursty()).await;

	let publisher = moq_tokio::origin::spawn();
	let broadcast = publisher.create_broadcast("live").expect("create broadcast");
	broadcast.announce(Default::default()).expect("announce broadcast");
	let mut track = broadcast.create_track(TRACK, None).expect("create track");
	let url = publish_path.url.clone();
	let publish_session = tokio::time::timeout(
		TIMEOUT,
		client_over(&url, credit(lane, quic()))
			.with_publisher(&publisher)
			.with_reconnect(false)
			.connect(url)
			.established(),
	)
	.await
	.expect("publisher connect timed out")
	.expect("publisher connect failed");

	let subscriber = moq_tokio::origin::spawn();
	let subscribed = subscriber.consume();
	let url = subscribe_path.url.clone();
	let subscribe_session = tokio::time::timeout(
		TIMEOUT,
		client_over(&url, credit(lane, quic()))
			.with_subscriber(subscriber)
			.with_reconnect(false)
			.connect(url)
			.established(),
	)
	.await
	.expect("subscriber connect timed out")
	.expect("subscriber connect failed");

	// Subscribed before the first burst, as an app watching a control channel is.
	let mut reader = subscribe(&subscribed, "live").await;

	let total = BURSTS * BURST_GROUPS;
	let mut written = Vec::new();
	let burst = |track: &mut moq_net::track::Producer, written: &mut Vec<tokio::time::Instant>| {
		for _ in 0..BURST_GROUPS {
			let sequence = written.len() as u64;
			write_group(track, &payload(sequence));
			written.push(tokio::time::Instant::now());
		}
	};
	burst(&mut track, &mut written);

	// Each group is claimed once, by the subscription or by a FETCH, and settles
	// in `pending`. A live group that fails is a gap like any other, so it is
	// FETCHed in turn.
	let mut claimed = std::collections::BTreeSet::new();
	let mut live = std::collections::BTreeSet::new();
	let mut outcomes = std::collections::BTreeMap::new();
	let mut pending = tokio::task::JoinSet::new();
	let mut resets = Vec::new();
	let mut slowest = (Duration::ZERO, 0);
	let fetch = |pending: &mut tokio::task::JoinSet<_>, track: &moq_net::track::Consumer, sequence: u64| {
		let fetching = track.fetch_group(sequence, None);
		pending.spawn(async move {
			let fetched = tokio::time::timeout(SETTLE, async {
				let group = fetching.await.map_err(|err| err.to_string())?;
				read_payload(group, sequence).await
			});
			let outcome = match fetched.await {
				Ok(Ok(())) => Outcome::Fetched,
				Ok(Err(err)) => Outcome::Failed(err),
				Err(_) => Outcome::Unanswered,
			};
			(sequence, outcome)
		});
	};

	while (outcomes.len() as u64) < total {
		let step = tokio::time::timeout(SETTLE, async {
			tokio::select! {
				group = reader.groups.recv_group() => Step::Group(Box::new(group)),
				Some(settled) = pending.join_next() => {
					let (sequence, outcome) = settled.expect("settle task panicked");
					Step::Settled(sequence, outcome)
				}
			}
		})
		.await
		.unwrap_or_else(|_| {
			let missing: Vec<u64> = (0..total).filter(|sequence| !outcomes.contains_key(sequence)).collect();
			panic!(
				"stalled: nothing arrived within {SETTLE:?}, {} of {total} groups missing: {missing:?}",
				missing.len()
			)
		});

		match step {
			Step::Settled(sequence, Outcome::Failed(err)) if live.remove(&sequence) => {
				resets.push((sequence, err));
				fetch(&mut pending, &reader.track, sequence);
			}
			Step::Settled(sequence, outcome) => {
				live.remove(&sequence);
				let late = written[sequence as usize].elapsed();
				slowest = slowest.max((late, sequence));
				outcomes.insert(sequence, outcome);
			}
			Step::Group(group) => {
				let group = (*group)
					.unwrap_or_else(|err| panic!("the subscription aborted: {err}"))
					.unwrap_or_else(|| panic!("the subscription finished"));
				let sequence = group.sequence;

				// Every unclaimed group below this one is a gap the subscription
				// skipped: FETCH it now rather than wait.
				for gap in 0..sequence {
					if claimed.insert(gap) {
						fetch(&mut pending, &reader.track, gap);
					}
				}
				if claimed.insert(sequence) {
					live.insert(sequence);
					pending.spawn(async move {
						let outcome = match tokio::time::timeout(SETTLE, read_payload(group, sequence)).await {
							Ok(Ok(())) => Outcome::Live,
							Ok(Err(err)) => Outcome::Failed(err),
							Err(_) => Outcome::Stalled,
						};
						(sequence, outcome)
					});
				}

				// The next burst leaves once this one starts arriving, so recovery
				// overlaps fresh data the way a busy control channel's does.
				if sequence + BURST_GROUPS >= written.len() as u64 && (written.len() as u64) < total {
					burst(&mut track, &mut written);
				}
			}
		}
	}

	// Fault activation: the subscription skipped or reset groups, so the FETCH
	// recovery below had something to recover.
	let gaps = outcomes
		.values()
		.filter(|outcome| !matches!(outcome, Outcome::Live))
		.count();
	println!(
		"fault activated: {gaps} of {total} groups missed the live subscription (reset: {resets:?}), slowest group {} after {:?}",
		slowest.1, slowest.0
	);
	assert!(gaps > 0, "every group came live, so no FETCH recovery was exercised");

	let lost: Vec<_> = outcomes
		.iter()
		.filter(|(_, outcome)| !matches!(outcome, Outcome::Live | Outcome::Fetched))
		.collect();
	assert!(lost.is_empty(), "groups lost: {lost:?}");
	assert!(
		slowest.0 <= SETTLE,
		"group {} took {:?} to arrive, past {SETTLE:?}",
		slowest.1,
		slowest.0
	);
	assert!(
		matches!(outcomes.get(&(total - 1)), Some(Outcome::Live)),
		"the newest group came by {:?}, not the live subscription",
		outcomes.get(&(total - 1))
	);

	drop(reader);
	drop(subscribe_session);
	drop(publish_session);
	drop(edge);
	drop(origin);
	peer.verify();
	publish_path.verify();
	subscribe_path.verify();
}

lanes!(bursts_cross_a_cluster);

/// Negative control: with nothing publishing, the drills' delivery assertions
/// have to fail.
///
/// Every drill above proves something by reading a frame. This one runs the same
/// harness with no publisher and requires that no announcement and no broadcast
/// ever arrive, so "the frame showed up" cannot be a harness artifact.
async fn no_publisher_never_delivers(lane: Lane) {
	let relay = RelayHost::start(relay_config(None)).await;
	let path = Path::start(lane, &relay).await;
	let url = path.url.clone();

	let subscriber = moq_tokio::origin::spawn();
	let subscribed = subscriber.consume();
	let session = tokio::time::timeout(
		TIMEOUT,
		client(&url)
			.with_subscriber(subscriber)
			.with_reconnect(false)
			.connect(url.clone())
			.established(),
	)
	.await
	.expect("subscriber connect timed out")
	.expect("subscriber connect failed");

	// Short on purpose: this is the one wait that must expire, so it is the one
	// wait that decides how long the suite spends proving a negative.
	let quiet = Duration::from_secs(2);

	let mut announced = subscribed.announced();
	if let Ok(update) = tokio::time::timeout(quiet, next_update(&mut announced)).await {
		let path = update.map(|(update, _)| update.prefix.to_string());
		panic!("the announcement stream reported {path:?} with no publisher");
	}

	assert!(
		tokio::time::timeout(quiet, subscribed.routed_broadcast("live"))
			.await
			.is_err(),
		"a broadcast resolved with no publisher"
	);

	drop(session);
	drop(relay);
	path.verify();
}

lanes!(no_publisher_never_delivers);

/// The next route and whether it is active, skipping the caught-up marker.
async fn next_update(announced: &mut moq_net::announce::Consumer) -> Option<(moq_net::announce::Announce, bool)> {
	loop {
		return match announced.next().await? {
			moq_net::announce::Event::Start(route) | moq_net::announce::Event::Update(route) => Some((route, true)),
			moq_net::announce::Event::End(route) => Some((route, false)),
			moq_net::announce::Event::Live => continue,
		};
	}
}
