//! Raw `videodev2.h` bindings, generated by [bindgen](https://github.com/rust-lang/rust-bindgen)
//! via `bindgen.sh` and checked in. The output is plain C-ABI struct, enum, and
//! constant definitions with no layout tests, and `timeval` / `timespec` come
//! from `libc`, so one file serves every Linux target.
#![allow(clippy::all)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

include!("videodev2.rs");
