set shell := ["bash", "-euo", "pipefail", "-c"]

# Run the web server targetting the specified relay
default url='http://localhost:4443/anon':
	VITE_RELAY_URL="{{url}}" bun run --filter @moq/demo dev
