// Generated by the scalar LLBC prototype. Do not edit.
import { U64 } from "../../../js/net/src/util/u64";
import { and, neg, sar, shl, shr, xor } from "./runtime";

/** Translated from moq_net::coding::varint::zigzag; i64 values use two's complement U64 bits. */
export function zigzag(v1: U64): U64 {
	const v4: U64 = v1;
	const v5: number = 1 >>> 0;
	const v6: boolean = v5 < 64;
	if (v6 !== true) throw new Error("Rust assertion failed");
	const v3: U64 = shl(v4, 1);
	const v8: U64 = v1;
	const v9: number = 63 >>> 0;
	const v10: boolean = v9 < 64;
	if (v10 !== true) throw new Error("Rust assertion failed");
	const v7: U64 = sar(v8, 63);
	const v2: U64 = xor(v3, v7);
	const v0: U64 = v2;
	return v0;
}

/** Translated from moq_net::coding::varint::unzigzag; i64 values use two's complement U64 bits. */
export function unzigzag(v1: U64): U64 {
	const v4: U64 = v1;
	const v5: number = 1 >>> 0;
	const v6: boolean = v5 < 64;
	if (v6 !== true) throw new Error("Rust assertion failed");
	const v3: U64 = shr(v4, 1);
	const v2: U64 = v3;
	const v10: U64 = v1;
	const v9: U64 = and(v10, new U64(0, 1));
	const v8: U64 = v9;
	const v11: boolean = v8.equals(new U64(2147483648, 0));
	if (v11 !== false) throw new Error("Rust assertion failed");
	const v7: U64 = neg(v8);
	const v0: U64 = xor(v2, v7);
	return v0;
}
