[package]
name = "moq-native"
description = "Deprecated: use moq-tokio instead"
authors = ["Luke Curley"]
repository = "https://github.com/moq-dev/moq"
license = "MIT OR Apache-2.0"

version = "0.19.11"
edition = "2024"
rust-version.workspace = true

keywords = ["quic", "http3", "webtransport", "media", "live"]
categories = ["multimedia", "network-programming", "web-programming"]

[features]
default = ["quinn", "aws-lc-rs", "websocket", "tcp", "uds"]
quinn = []
noq = []
quiche = []
watch = []
qlog = []
aws-lc-rs = []
iroh = []
mdns = []
jemalloc = []
websocket = []
tcp = []
uds = []
ring = []
android-logcat = []
