[package]
name = "moq-token"
description = "Media over QUIC - Token Generation and Validation"
authors = ["Luke Curley"]
repository = "https://github.com/moq-dev/moq"
license = "MIT OR Apache-2.0"

version = "0.7.2"
edition = "2024"
rust-version.workspace = true

[features]
jwks-loader = ["reqwest"]
tokio = ["dep:tokio"]

[dependencies]
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }
p256 = "0.14.0"
p384 = "0.14.0"
reqwest = { workspace = true, features = ["rustls"], optional = true }
rsa = "0.9.10"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"], optional = true }

[dev-dependencies]
anyhow = { workspace = true }
