[package]
name = "libmoq"
description = "Renamed to moq-c: Media over QUIC, C bindings"
authors = ["Luke Curley <kixelated@gmail.com>", "Brian Medley <bpm@bmedley.org>"]
repository = "https://github.com/moq-dev/moq"
license = "MIT OR Apache-2.0"

version = "0.6.9"
edition = "2024"
rust-version.workspace = true

keywords = ["quic", "media", "live"]
categories = ["multimedia", "network-programming"]
