# List all of the available commands.
default:
  just --list

# Initialize tofu providers and backend
init:
	tofu init

deploy:
	tofu apply

check:
	tofu fmt -check -recursive

fix:
	tofu fmt -recursive
