set fallback
set shell := ["bash", "-euo", "pipefail", "-c"]

relay_url := 'http://localhost:4443/anon'

# Run the robotics demo: relay + robo publisher + web viewer.
default:
	bun install

	bun run concurrently --kill-others --names srv,robo,web --prefix-colors auto \
		"just relay" \
		"sleep 1 && just wait && just pub" \
		"sleep 2 && just wait && just web"

# Add another robo publisher to an already-running relay.
pub url='http://localhost:4443/anon':
	cargo run --bin moq-robo -- --url {{url}} --media-dir "../media/robo"

# Host the web server
web url='http://localhost:4443/anon':
	VITE_RELAY_URL={{url}} bun run --filter @moq/robo dev --open
